# Generated by Django 4.2.30 on 2026-04-09 13:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('working_hours', models.TextField(verbose_name='Ish vaqti')),
            ],
            options={
                'verbose_name': "Aloqa ma'lumotlari",
                'verbose_name_plural': "Aloqa ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('image', models.ImageField(upload_to='gallery_images/', verbose_name='Rasm')),
                ('category', models.CharField(choices=[('rooms', 'Xonalar'), ('restaurant', 'Restoran'), ('spa', 'SPA & Fitness'), ('events', 'Tadbirlar'), ('other', 'Boshqa')], max_length=20, verbose_name='Kategoriya')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Galereya rasmi',
                'verbose_name_plural': 'Galereya rasmlari',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('room_type', models.CharField(choices=[('standard', 'Standard Xona'), ('deluxe', 'Deluxe Xona'), ('suite', 'Suite Xona'), ('family', 'Oila uchun Xona'), ('presidential', 'Prezidentlik Xona'), ('business', 'Business Xona')], max_length=20, verbose_name='Xona turi')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Qisqa tavsif')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name="Narx (so'm)")),
                ('image', models.ImageField(upload_to='room_images/', verbose_name='Asosiy rasm')),
                ('description', ckeditor.fields.RichTextField(verbose_name="To'liq tavsif")),
                ('area', models.CharField(max_length=50, verbose_name='Maydoni')),
                ('bed_type', models.CharField(max_length=100, verbose_name='Krevat turi')),
                ('features', models.JSONField(default=list, verbose_name='Imkoniyatlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xona',
                'verbose_name_plural': 'Xonalar',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('icon', models.CharField(max_length=50, verbose_name='Icon klassi (FontAwesome)')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='F.I.Sh.')),
                ('position', models.CharField(max_length=200, verbose_name='Lavozim')),
                ('image', models.ImageField(upload_to='staff_images/', verbose_name='Rasm')),
                ('bio', models.TextField(verbose_name='Biografiya')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['order'],
            },
        ),
    ]
