# Generated by Django 4.2.30 on 2026-04-09 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('contact_method', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], max_length=10, verbose_name='Aloqa usuli')),
                ('check_in', models.DateField(blank=True, null=True, verbose_name='Kelish sanasi')),
                ('check_out', models.DateField(blank=True, null=True, verbose_name='Ketish sanasi')),
                ('message', models.TextField(blank=True, verbose_name='Xabar')),
                ('is_processed', models.BooleanField(default=False, verbose_name="Ko'rib chiqildi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room', verbose_name='Xona')),
            ],
            options={
                'verbose_name': 'Bron',
                'verbose_name_plural': 'Bronlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
