# Generated by Django 4.2.30 on 2026-04-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='country_code',
            field=models.CharField(choices=[('+998', "🇺🇿 O'zbekiston (+998)"), ('+7', '🇷🇺 Rossiya (+7)'), ('+1', '🇺🇸 AQSh (+1)'), ('+44', '🇬🇧 Buyuk Britaniya (+44)'), ('+49', '🇩🇪 Germaniya (+49)'), ('+90', '🇹🇷 Turkiya (+90)'), ('+86', '🇨🇳 Xitoy (+86)'), ('+91', '🇮🇳 Hindiston (+91)'), ('+81', '🇯🇵 Yaponiya (+81)'), ('+82', '🇰🇷 Koreya (+82)'), ('+971', '🇦🇪 BAA (+971)'), ('+992', '🇹🇯 Tojikiston (+992)'), ('+993', '🇹🇲 Turkmaniston (+993)'), ('+996', "🇰🇬 Qirg'iziston (+996)"), ('+994', '🇦🇿 Ozarbayjon (+994)'), ('+375', '🇧🇾 Belarus (+375)'), ('+380', '🇺🇦 Ukraina (+380)'), ('+48', '🇵🇱 Polsha (+48)'), ('+39', '🇮🇹 Italiya (+39)'), ('+33', '🇫🇷 Fransiya (+33)'), ('+34', '🇪🇸 Ispaniya (+34)')], default='+998', max_length=5, verbose_name='Davlat kodi'),
        ),
    ]
